### ISSUE TITLE
github.com linked via phoenix.yizimg.com proxy/phishing

### ISSUE THREAD

**Issue by kurahaupo** [sseen/sseen.github.io#2]
Your [index.html](https://github.com/sseen/sseen.github.io/blob/d2605da7143971db7a85cbffc47d9812d17b195b/iOS%E7%B1%BBSS%E5%AE%A2%E6%88%B7%E7%AB%AF%20macOS%20Big%20Sur%20%E4%B8%8B%E7%BC%96%E8%AF%91/index.html) contains a link to `https://phoenix.yizimg.com` which appears to be a proxy for `github.com`.

It is suspected of being a phishing site to obtain usernames and passwords of github.com users.

Please edit and link directly to github.com

**Comment by sseen** [comment]
Sorry for replying so late, thank you for your reminder, it has been fixed
